### ISSUE TITLE
Don't spendable values

### ISSUE THREAD

**Issue by machado-rev** [MatthewLM/peercoin-android-wallet#10]
Hello, I am compiling with success and are installing and running good my wallet based on Peercoin Wallet, but not confirm yet. I attach the debugger to Android system and get this:

http://pastebin.com/uWLVteY9

What you think that I need to do @MatthewLM ???

**Comment by MatthewLM** [comment]
You ought to filter your logcat output to `com.bushstar.htmlcoin_android_wallet`, but this appears to be your problem (ie. You are not connecting to the getvalidhashes API).

```
03-30 08:54:55.743  14566-14598/com.bushstar.htmlcoin_android_wallet E/AbstractBlockChain﹕ [NioClientManager] IO Error when determining valid hashes:
    java.net.ConnectException: failed to connect to html.machadocrypto.com/64.57.133.2 (port 80) after 8000ms: isConnected failed: ECONNREFUSED (Connection refused)
            at libcore.io.IoBridge.isConnected(IoBridge.java:272) ~[na:0.0]
            at libcore.io.IoBridge.connectErrno(IoBridge.java:210) ~[na:0.0]
            at libcore.io.IoBridge.connect(IoBridge.java:128) ~[na:0.0]
            at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:192) ~[na:0.0]
            at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:460) ~[na:0.0]
            at java.net.Socket.connect(Socket.java:833) ~[na:0.0]
            at com.android.okhttp.internal.Platform.connectSocket(Platform.java:131) ~[na:0.0]
            at com.android.okhttp.Connection.connect(Connection.java:101) ~[na:0.0]
            at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:294) ~[na:0.0]
            at com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:255) ~[na:0.0]
            at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:206) ~[na:0.0]
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345) ~[na:0.0]
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:89) ~[na:0.0]
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:197) ~[na:0.0]
            at com.bushstar.htmlcoinj.store.ValidHashStore.isValidHash(ValidHashStore.java:180) ~[na:0.0]
            at com.bushstar.htmlcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:405) ~[na:0.0]
            at com.bushstar.htmlcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:257) ~[na:0.0]
            at com.bushstar.htmlcoinj.core.Peer.processHeaders(Peer.java:487) ~[na:0.0]
            at com.bushstar.htmlcoinj.core.Peer.processMessage(Peer.java:331) ~[na:0.0]
            at com.bushstar.htmlcoinj.core.PeerSocketHandler.receiveBytes(PeerSocketHandler.java:144) ~[na:0.0]
            at com.bushstar.htmlcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:216) ~[na:0.0]
            at com.bushstar.htmlcoinj.net.NioClientManager.handleKey(NioClientManager.java:74) ~[na:0.0]
            at com.bushstar.htmlcoinj.net.NioClientManager.run(NioClientManager.java:110) ~[na:0.0]
            at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:60) ~[na:0.0]
            at com.google.common.util.concurrent.Callables$3.run(Callables.java:93) ~[na:0.0]
            at java.lang.Thread.run(Thread.java:841) ~[na:0.0]
     Caused by: libcore.io.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
            at libcore.io.IoBridge.isConnected(IoBridge.java:257) ~[na:0.0]
    ... 25 common frames omitted
```

**Comment by machado-rev** [comment]
@MatthewLM this is only the ticker of price I think, I am redoing the system from zero to test.
Back soon with more informations, Thank you for you reply
