### ISSUE TITLE
Android wallet crashes on start (small delay before crash)

### ISSUE THREAD

**Issue by kobocoin** [MatthewLM/peercoin-android-wallet#11]
Hi, I'm having a problem getting the android wallet to load on a phone. It's not an immediate crash. It appears to be loading for about 1-2 secs and then fails with a JNI error.

When I run the kobocoin android application I see the following adb output:

    F/art     (26408): art/runtime/runtime.cc:284] "GCDaemon" prio=5 tid=9 Waiting
    F/art     (26408): art/runtime/runtime.cc:284]   | group="" sCount=0 dsCount=0 obj=0x12c3d200 self=0xb7817508
    F/art     (26408): art/runtime/runtime.cc:284]   | sysTid=26423 nice=0 cgrp=apps sched=0/0 handle=0xb7817ac8
    F/art     (26408): art/runtime/runtime.cc:284]   | state=S schedstat=( 0 0 0 ) utm=0 stm=0 core=0 HZ=100
    F/art     (26408): art/runtime/runtime.cc:284]   | stack=0xa73db000-0xa73dd000 stackSize=1036KB
    F/art     (26408): art/runtime/runtime.cc:284]   | held mutexes=
    F/art     (26408): art/runtime/runtime.cc:284]   kernel: futex_wait_queue_me+0xe0/0x108
    F/art     (26408): art/runtime/runtime.cc:284]   kernel: futex_wait+0x170/0x238
    F/art     (26408): art/runtime/runtime.cc:284]   kernel: do_futex+0xfc/0x9fc
    F/art     (26408): art/runtime/runtime.cc:284]   kernel: ret_fast_syscall+0x0/0x30
    F/art     (26408): art/runtime/runtime.cc:284]   native: #02 pc 0001f39b  /system/lib/libbinder.so (android::IPCThreadState::talkWithDriver(bool)+138)
    F/art     (26408): art/runtime/runtime.cc:284]   native: #04 pc 0001f8ed  /system/lib/libbinder.so (android::IPCThreadState::joinThreadPool(bool)+48)
    F/art     (26408): art/runtime/runtime.cc:284]   native: #06 pc 000104fd  /system/lib/libutils.so (android::Thread::_threadLoop(void*)+112)
    F/art     (26408): art/runtime/runtime.cc:284]   native: #08 pc 000100d3  /system/lib/libutils.so (???)
    F/art     (26408): art/runtime/runtime.cc:284]   native: #10 pc 00013e37  /system/lib/libc.so (__start_thread+6)
    F/art     (26408): art/runtime/runtime.cc:284] 
    F/libc    (26408): Fatal signal 6 (SIGABRT), code -6 in tid 26408 (_android_wallet)
    I/DEBUG   (  271): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
    I/DEBUG   (  271): Build fingerprint: 'motorola/falcon_retgb/falcon_umts:5.0.2/LXB22.46-28.1/1:user/release-keys'
    I/DEBUG   (  271): Revision: 'p3c0'
    I/DEBUG   (  271): ABI: 'arm'
    I/DEBUG   (  271): pid: 26408, tid: 26408, name: _android_wallet  >>> com.machadocrypto.kobocoin_android_wallet <<<
    I/DEBUG   (  271): signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
    I/DEBUG   (  271): Abort message: 'art/runtime/check_jni.cc:65] JNI DETECTED ERROR IN APPLICATION: JNI RegisterNatives called with pending exception 'java.lang.ClassNotFoundException' thrown in unknown throw location'
    I/DEBUG   (  271):     r0 00000000  r1 00006728  r2 00000006  r3 00000000
    I/DEBUG   (  271):     r4 b6f66114  r5 00000006  r6 0000000b  r7 0000010c
    I/DEBUG   (  271):     r8 00000000  r9 b7604908  sl b760e4c0  fp 00000001
    I/DEBUG   (  271):     ip 00006728  sp beb9e9b0  lr b6f01679  pc b6f26c30  cpsr 60070010
    I/DEBUG   (  271): 
    I/DEBUG   (  271): backtrace:
    I/DEBUG   (  271):     #00 pc 0003bc30  /system/lib/libc.so (tgkill+12)
    I/DEBUG   (  271):     #01 pc 00016675  /system/lib/libc.so (pthread_kill+52)
    I/DEBUG   (  271):     #02 pc 00017287  /system/lib/libc.so (raise+10)
    I/DEBUG   (  271):     #03 pc 00013ad9  /system/lib/libc.so (__libc_android_abort+36)
    I/DEBUG   (  271):     #04 pc 00012264  /system/lib/libc.so (abort+4)
    I/DEBUG   (  271):     #05 pc 0022f2e3  /system/lib/libart.so (art::Runtime::Abort()+170)
    I/DEBUG   (  271):     #06 pc 000a7109  /system/lib/libart.so (art::LogMessage::~LogMessage()+1360)
    I/DEBUG   (  271):     #07 pc 000b1217  /system/lib/libart.so (art::JniAbort(char const*, char const*)+1102)
    I/DEBUG   (  271):     #08 pc 000b1751  /system/lib/libart.so (art::JniAbortF(char const*, char const*, ...)+68)
    I/DEBUG   (  271):     #09 pc 000b49d7  /system/lib/libart.so (art::ScopedCheck::ScopedCheck(_JNIEnv*, int, char const*)+1322)
    I/DEBUG   (  271):     #10 pc 000bf6a5  /system/lib/libart.so (art::CheckJNI::RegisterNatives(_JNIEnv*, _jclass*, JNINativeMethod const*, int)+36)
    I/DEBUG   (  271):     #11 pc 00003637  /data/app/com.machadocrypto.kobocoin_android_wallet-1/lib/arm/libx15.so (JNI_OnLoad+42)
    I/DEBUG   (  271):     #12 pc 001e6757  /system/lib/libart.so (art::JavaVMExt::LoadNativeLibrary(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, art::Handle<art::mirror::ClassLoader>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*)+1610)
    I/DEBUG   (  271):     #13 pc 0020e14f  /system/lib/libart.so (art::Runtime_nativeLoad(_JNIEnv*, _jclass*, _jstring*, _jobject*, _jstring*)+534)
    I/DEBUG   (  271):     #14 pc 00077c99  /system/framework/arm/boot.oat
    W/ActivityManager(  873): Process com.machadocrypto.kobocoin_android_wallet has crashed too many times: killing!
    I/DEBUG   (  271): 
    I/DEBUG   (  271): Tombstone written to: /data/tombstones/tombstone_08
    I/BootReceiver(  873): Copying /data/tombstones/tombstone_08 to DropBox (SYSTEM_TOMBSTONE)
    W/ActivityManager(  873):   Force finishing activity com.machadocrypto.kobocoin_android_wallet/.WalletActivity
    W/WindowManager(  873): Failed looking up window
    W/WindowManager(  873): java.lang.IllegalArgumentException: Requested window android.view.ViewRootImpl$W@1a0a87af does not exist
    W/WindowManager(  873): 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8457)
    W/WindowManager(  873): 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8448)
    W/WindowManager(  873): 	at com.android.server.wm.WindowManagerService.removeWindow(WindowManagerService.java:2574)
    W/WindowManager(  873): 	at com.android.server.wm.Session.remove(Session.java:186)
    W/WindowManager(  873): 	at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:2959)
    W/WindowManager(  873): 	at android.view.ViewRootImpl.doDie(ViewRootImpl.java:5460)
    W/WindowManager(  873): 	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3283)
    W/WindowManager(  873): 	at android.os.Handler.dispatchMessage(Handler.java:102)
    W/WindowManager(  873): 	at android.os.Looper.loop(Looper.java:135)
    W/WindowManager(  873): 	at android.os.HandlerThread.run(HandlerThread.java:61)
    W/WindowManager(  873): 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
    W/ActivityManager(  873): Wtf, activity ActivityRecord{d0ea2ea u0 com.machadocrypto.kobocoin_android_wallet/.WalletActivity t108 f} in proc activity list not using proc ProcessRecord{3bd79516 26408:com.machadocrypto.kobocoin_android_wallet/u0a176}?!?
    E/lowmemorykiller(  256): Error writing /proc/26408/oom_score_adj; errno=22
    E/JavaBinder(  873): !!! FAILED BINDER TRANSACTION !!!
    E/JavaBinder(  873): !!! FAILED BINDER TRANSACTION !!!
    W/ContextImpl( 1506): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1455 android.content.ContextWrapper.sendBroadcast:376 com.motorola.motocare.util.TriggerHelper$TriggerBuilder.send:76 com.motorola.motocare.internal.frameworkevents.PauseResumeTrigger.handleFrameworkEvent:53 com.motorola.motocare.internal.frameworkevents.FwEventMonitor$FrameworkListener.processFrameworkEvent:114 
    I/SFPerfTracer(  259):      triggers: (rate: 49:460874) (526 sw vsyncs) (622398 skipped) (11:187640 vsyncs) (13:208232)
    I/SFPerfTracer(  259):      triggers: (rate: 0:2) (0 sw vsyncs) (0 skipped) (0:22088 vsyncs) (1:210091)
    I/ActivityManager(  873): Killing 26408:com.machadocrypto.kobocoin_android_wallet/u0a176 (adj 9): crash
    I/Zygote  (  288): Process 26408 exited due to signal (6)
    W/ActivityManager(  873): Spurious death for ProcessRecord{3bd79516 26408:com.machadocrypto.kobocoin_android_wallet/u0a176}, curProc for 26408: null
    I/MDMCTBK (  272): NetlinkHandler, power_supply subsys
    
Any ideas what may be causing this? The merkle hash has calculated correctly so I'm not sure what is causing this. I've noticed that other wallets are using the Adreno SDK engine. Is this something I need to do?

**Comment by machado-rev** [comment]
this is related to your X15 libs I THINK, now I finish the Htmlcoin and will see your coin! Sorry for delay!

@MatthewLM you know how to format money to 8 digits on sending?

Thank you

**Comment by kobocoin** [comment]
Yes, I'll try writing it tonight. I'm just setting up a new build path before starting.
